<a href="https://colab.research.google.com/github/DeadOnGames/Q-Learning-Frozen-Lake-Reinforcement-Learning/blob/main/Q_Learning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install pygame

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 21.8 MB 1.6 MB/s 


In [ ]:
! pip install gym[toy_text]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 18.3 MB 31 kB/s 
  Attempting uninstall: pygame
    Found existing installation: pygame 2.1.2
    Uninstalling pygame-2.1.2:
      Successfully uninstalled pygame-2.1.2


In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make("FrozenLake-v1");

/usr/local/lib/python3.8/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.8/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

#Epsilon Greedy Strategy
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size));
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
rewards_all_episodes = []

#Q-Learning Algorithnm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    #Timestep within each episode
    for step in range(max_steps_per_episode):
        
        #Exploration-exploitation trade off
        exploration_rate_threshold = random.uniform(0,1);
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state,action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        #q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]) - q_table[state, action])
                             
        state = new_state
        rewards_current_episode += reward
                             
        if done == True:
            break

In [ ]:
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)
                                                             

In [ ]:
    #Calculate and print the avergae reward per thousand episodes
    rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/10000)
    count = 10000
    print("*****Average reward per thousand episodes*****\n")
    for r in rewards_per_thousand_episodes:
        print(count, ": ", str(sum(r/10000)))
        count += 10000

*****Average reward per thousand episodes*****

10000 :  0.0


In [ ]:
#Print an updated Q-table
print("\n\n*****Q-Table*****\n")
print(q_table)



*****Q-Table*****

[[0.57656118 0.5604676  0.55647621 0.55637809]
 [0.32771863 0.27577658 0.33724185 0.52473924]
 [0.46620801 0.44222372 0.44357288 0.47795434]
 [0.35545319 0.36714394 0.35301769 0.45899049]
 [0.59890511 0.39906052 0.43760313 0.42194436]
 [0.         0.         0.         0.        ]
 [0.43486018 0.24342429 0.29692748 0.19182954]
 [0.         0.         0.         0.        ]
 [0.32121725 0.52017932 0.40606843 0.61756752]
 [0.42283793 0.68302862 0.5636034  0.47316091]
 [0.61197302 0.37925607 0.43909513 0.41151429]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43132727 0.43530457 0.7647102  0.55447989]
 [0.75214861 0.86933666 0.82617734 0.7437218 ]
 [0.         0.         0.         0.        ]]


In [ ]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****Episode ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        #env.render()
        gym.make("FrozenLake-v1", render_mode='human')
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        
        #Take the best action
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            gym.make("FrozenLake-v1", render_mode='human')
            if reward == 1:
                print("*****You reached the goal*****")
                time.sleep(3)
            else:
                print("*****You fell through a hole*****")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

*****You fell through a hole*****
